/**:
  ros__parameters:
    fcu_url: "udp://:14540@127.0.0.1:14557" # Autopilot address for connection
    gcs_url: "" # URL for the GCS
    tgt_system: 1 # Target system ID
    tgt_component: 1 # Target component ID
    log_output: "screen" # Logging output type
    fcu_protocol: "v2.0" # Protocol version for the FCU
    respawn_mavros: "false" # Respawn mavros node if it dies
